# Logo
logo_image_source: https://raw.githubusercontent.com/seumsc/pages/master/res/MSCWeb.png

# Index Page
index_banner_text: Microsoft Student Club @ SEU ~
index_banner_text_secondary: Empower every person
index_font_awesome_icon_css: fa fa-magic

# Header
menu:
  Home: /
  Archives: /archives
  # Tags: /tags
  # Categories: /categories
  # About: /about.html
  # Contact: /contact.html

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: https://raw.githubusercontent.com/seumsc/pages/master/res/MSCWeb.png
about_widget_text: "这里是位于东南大学九龙湖校区的微软学生俱乐部，我们欢迎每个感兴趣的同学参与活动，予力众生，成就非凡。"


# Comments.
comments:
  # Disqus comments
  # disqus_shortname:

# Google Analytics Tracking ID
# google_analytics:

# Social Media Platforms
social_platforms:
  # - url: https://twitter.com/?lang=en
  #   fa_icon: fa-twitter
  # - url: https://www.facebook.com/
  #   fa_icon: fa-facebook
  # - url: https://dribbble.com/
  #   fa_icon: fa-dribbble
  - url: https://github.com/seumsc
    fa_icon: fa-github
  # - url: https://plus.google.com/
  #   fa_icon: fa-google-plus
  # - url: https://www.behance.net/
  #   fa_icon: fa-behance
  # - url: https://500px.com/
  #   fa_icon: fa-500px
  # - url: mailto:test@example.com
  #   fa_icon: fa-envelope
  # - url: /#
  #   fa_icon: fa-rss

# Footer about
footer_about: "@Microsoft Student Club @ SEU. All right reserved <a href =\"mailto:MSC_SEU@outlook.com\">Contact us</a>"
